name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-18.04]

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: make

    - name: Package
      run: tar cjf ${{github.workspace}}/melis-utils-${{matrix.os}}.tar.bz2 ${{github.workspace/bin}} ${{github.workspace/*.sh}}

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: melis-utils-${{matrix.os}}.tar.bz2
        path: melis-utils-${{matrix.os}}.tar.bz2
        retention-days: 90
