name: Makefile CI

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-20.04]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build
      run: make

    - name: Package
      run: tar cjf ${{github.workspace}}/melis-utils-${{matrix.os}}.tar.bz2 ${{github.workspace}}/bin ${{github.workspace}}/*.sh

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: melis-utils-${{matrix.os}}.tar.bz2
        path: melis-utils-${{matrix.os}}.tar.bz2
        retention-days: 1
        
  package:
    if: always() && ${{github.event.ref_type}} == 'tag'
    runs-on: ubuntu-20.04
    needs: build
    permissions:
      contents: write
      
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: melis-utils-macos-10.15.tar.bz2
        
    - uses: actions/download-artifact@v3
      with:
        name: melis-utils-ubuntu-20.04.tar.bz2
        
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "*.tar.bz2"
